// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentAssignment struct {
	ID                    pgtype.UUID      `json:"id"`
	UserID                pgtype.UUID      `json:"user_id"`
	AgentIDReference      string           `json:"agent_id_reference"`
	AllocationStrategy    string           `json:"allocation_strategy"`
	Priority              int32            `json:"priority"`
	MaxConcurrentRequests int32            `json:"max_concurrent_requests"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Quota struct {
	ID                   pgtype.UUID      `json:"id"`
	UserID               pgtype.UUID      `json:"user_id"`
	Tier                 string           `json:"tier"`
	MaxAgents            int32            `json:"max_agents"`
	MaxTokensPerDay      int64            `json:"max_tokens_per_day"`
	MaxRequestsPerDay    int32            `json:"max_requests_per_day"`
	MaxRequestsPerMinute int32            `json:"max_requests_per_minute"`
	UsedTokensToday      int32            `json:"used_tokens_today"`
	UsedRequestsToday    int32            `json:"used_requests_today"`
	ResetDate            pgtype.Timestamp `json:"reset_date"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type UsageMetric struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	AgentIDReference string           `json:"agent_id_reference"`
	TokensUsed       int64            `json:"tokens_used"`
	RequestsCount    int64            `json:"requests_count"`
	Cost             pgtype.Numeric   `json:"cost"`
	Timestamp        pgtype.Timestamp `json:"timestamp"`
}

type User struct {
	ID               pgtype.UUID      `json:"id"`
	Email            string           `json:"email"`
	Name             string           `json:"name"`
	SubscriptionTier string           `json:"subscription_tier"`
	IsActive         bool             `json:"is_active"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}
