// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAgentAssignment(ctx context.Context, arg CreateAgentAssignmentParams) (AgentAssignment, error)
	CreateQuota(ctx context.Context, arg CreateQuotaParams) (Quota, error)
	CreateUsageMetric(ctx context.Context, arg CreateUsageMetricParams) (UsageMetric, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAgentAssignment(ctx context.Context, id pgtype.UUID) error
	DeleteAgentAssignmentByUserAndAgent(ctx context.Context, arg DeleteAgentAssignmentByUserAndAgentParams) error
	DeleteQuota(ctx context.Context, userID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAgentAssignmentByID(ctx context.Context, id pgtype.UUID) (AgentAssignment, error)
	GetAgentAssignmentsByAgentID(ctx context.Context, agentIDReference string) ([]AgentAssignment, error)
	GetAgentAssignmentsByUserID(ctx context.Context, userID pgtype.UUID) ([]AgentAssignment, error)
	GetQuotaByUserID(ctx context.Context, userID pgtype.UUID) (Quota, error)
	GetTotalUsageByUser(ctx context.Context, userID pgtype.UUID) (GetTotalUsageByUserRow, error)
	GetUsageMetricsByUserID(ctx context.Context, arg GetUsageMetricsByUserIDParams) ([]UsageMetric, error)
	GetUsageMetricsByUserIDAndDateRange(ctx context.Context, arg GetUsageMetricsByUserIDAndDateRangeParams) ([]UsageMetric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ResetDailyQuota(ctx context.Context, resetDate pgtype.Timestamp) error
	UpdateQuota(ctx context.Context, arg UpdateQuotaParams) (Quota, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
